title: Wojtek builds web applications
email: wojtek@oxos.pl
description: >
  Wojtek Kruszewski builds web applications – SaaS ★ Maintenance ★ Subscriptions ★ Integrations
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kruszewski.com"
twitter_username: wojt_eu
github_username:  WojtekKruszewski

# Build settings
markdown: kramdown
